# Generated by Django 4.1.1 on 2022-10-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cedva1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='activo_por_pagos',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='snombreA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='Estado_pago',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='revicion'),
        ),
    ]
